Document: fuseflect2
Title: Debian fuseflect2 Manual
Author: <insert document author here>
Abstract: This manual describes what fuseflect2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fuseflect2/fuseflect2.sgml.gz

Format: postscript
Files: /usr/share/doc/fuseflect2/fuseflect2.ps.gz

Format: text
Files: /usr/share/doc/fuseflect2/fuseflect2.text.gz

Format: HTML
Index: /usr/share/doc/fuseflect2/html/index.html
Files: /usr/share/doc/fuseflect2/html/*.html
